/*
 * examineState.java
 *
 * Created on 4 July 2005, 06:26
 */

/**
 *
 * @author  Administrator
 */
public class examineState extends javax.swing.JFrame {
    
    /** Creates new form examineState */
    public examineState() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jList1 = new javax.swing.JList();
        jList2 = new javax.swing.JList();
        jList3 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jList4 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jList1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jList1);
        jList1.setBounds(20, 140, 150, 50);

        jList2.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jList2);
        jList2.setBounds(200, 140, 140, 50);

        jList3.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jList3);
        jList3.setBounds(20, 60, 150, 50);

        jLabel1.setText("Attributes:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 52, 14);

        jLabel2.setText("Values:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 120, 35, 14);

        jLabel3.setText("Class Instances:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 40, 150, 14);

        jLabel4.setText("Object Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 66, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Airport 5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 10, 50, 14);

        jList4.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jList4);
        jList4.setBounds(200, 60, 140, 50);

        jLabel6.setText("Waiting Events:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 40, 76, 14);

        jLabel7.setText("Current Action");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 300, 90, 14);

        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 320, 70);

        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 350, 320, 150);

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel8.setText("Do Something");
        jLabel8.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 300, 240, 18);

        jLabel9.setText("Preceeding Actions");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 200, 91, 20);

        jLabel10.setText("Proceeding Actions");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 330, 91, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Directing Traffic");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(250, 10, 90, 14);

        jLabel12.setText("Current State:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(170, 10, 70, 14);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examineState().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    
}
