/*
 * executeModel.java
 *
 * Created on 4 July 2005, 06:25
 */
package mockups;
/**
 *
 * @author  David Gavin
 */
public class executeModel extends javax.swing.JFrame {
    
    /** Creates new form executeModel */
    public executeModel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jScrollPane1.setDoubleBuffered(true);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setText("0 New Object created, instance(s): Manuscript, \\n 1 New Object created, instance(s): Manuscript, ");
        jTextArea1.setMaximumSize(new java.awt.Dimension(300, 300));
        jTextArea1.setMinimumSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 370, 150);

        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 30, 130, 90);

        jLabel1.setText("Object Pool:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 60, 14);

        jLabel2.setText("Model Execution:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 90, 14);

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\xtuml\\src\\mockups\\runIcon.jpg"));
        jToggleButton1.setText("Run");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(10, 20, 100, 20);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\xtuml\\src\\mockups\\pauseIcon.jpg"));
        jButton1.setText("Pause");
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 20, 100, 20);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\xtuml\\src\\mockups\\attIcon.jpg"));
        jButton2.setText("Set Attributes");
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 80, 130, 20);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\xtuml\\src\\mockups\\stepIcon.jpg"));
        jButton3.setText("Step");
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 50, 100, 20);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\xtuml\\src\\mockups\\stimIcon.jpg"));
        jButton4.setText("Event");
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 50, 100, 20);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new executeModel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    
}
