/*
 * guiLogging.java
 *
 * Created on 13 July 2005, 01:42
 */
package mockups;

import java.util.Vector;
import javax.swing.JFrame;
import metamodel.ActionBlock;
import metamodel.CreateAction;
import metamodel.Procedure;
import metamodel.Class;
import runtime.DomainContext;
import runtime.LemRuntimeException;
import runtime.Interpreter;
import verifier.JContextLoggerPanel;
/**
 *
 * @author  David Gavin
 */
public class guiLogging extends javax.swing.JFrame {
    Procedure p = new Procedure();
    ActionBlock aB = new ActionBlock();
    CreateAction a = new CreateAction();
    Class newClass = new Class();
    DomainContext d = new DomainContext();
    JContextLoggerPanel Logger = new JContextLoggerPanel(d);
    Interpreter I = new Interpreter(null);
    /** Creates new form guiLogging */
    public guiLogging() {
        newClass.setName("newClass");
        Vector c = new Vector();
        c.add(newClass);
        a.setClasses(c);
        aB.addAction(a);
        p.setActionBlock(aB);
        this.getContentPane().add(Logger, java.awt.BorderLayout.CENTER);
        //this.getContentPane().add(genButton, java.awt.BorderLayout.NORTH);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ExecuteProcedure();
        ExecuteProcedure();
        ExecuteProcedure();
    }
    public void ExecuteProcedure() {
        try{
            I.interpret(p, d);
        } catch(LemRuntimeException e) {
            System.out.println(e);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        genButton = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setName("LoggingPrototype");
        genButton.setText("generate");
        genButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genButtonMouseClicked(evt);
            }
        });

        getContentPane().add(genButton);
        genButton.setBounds(30, 20, 75, 23);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void genButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genButtonMouseClicked
        ExecuteProcedure();
    }//GEN-LAST:event_genButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiLogging().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genButton;
    // End of variables declaration//GEN-END:variables
    
}
