/*
 * ContextTreePanel.java
 *
 * Created on September 9, 2005, 1:28 PM
 */

package verifier;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author  shuku
 */
public class ContextTreePanel extends javax.swing.JPanel {
	
	/** the source context of this panel*/
	private runtime.Context context ;
	/** the description panel into which display the information
	 *about objects, instances etc.*/
	private DescriptionPanel descriptionPane ;
	/** the scenario that spawned the scenarioExecuter **/
	
	private LoggerFrame frame ; 
	
	/** Creates new form ContextTreePanel */
	/** creates a tree displaying all the major components in a context */
	public ContextTreePanel(runtime.Context c,  LoggerFrame frame) {
		initComponents();
		this.context = c ;
		this.frame = frame ; 
		ScenarioContextNode scenarioNode = new ScenarioContextNode( context,  frame) ;
		contextTree.setModel( new DefaultTreeModel( scenarioNode ));
		CustomTreeRenderer render = new CustomTreeRenderer();
		contextTree.setCellRenderer(render);
		add(contextTree ) ; 
	}
	
	/** Set a descriptionPane for this panel to write information into */
	public void setDescriptionPane(DescriptionPanel descriptionPane) {
		this.descriptionPane = descriptionPane;
	}
	
	/** get the jtree of this panel *
	 *@return JTree
	 */
	public JTree getTree() {
		return contextTree ; 
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        contextTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(150, 200));
        contextTree.setDragEnabled(true);
        contextTree.setEditable(true);
        contextTree.setPreferredSize(new java.awt.Dimension(150, 200));
        add(contextTree, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree contextTree;
    // End of variables declaration//GEN-END:variables
}
