/*
 * ContextTreePanel.java
 *
 * Created on September 9, 2005, 1:28 PM
 *
 * Copyright (C) 2005 Shokouhmand Torabi
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

package verifier;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author  Shokouhmand Torabi
 */
public class ContextTreePanel extends javax.swing.JPanel {
	
	/** the source context of this panel*/
	private runtime.Context context ;
	/** the description panel into which display the information
	 *about objects, instances etc.*/
	private JTextPane descriptionPane ;
	/** the scenario that spawned the scenarioExecuter **/
	
	private JPopupMenu contextMenu = new JPopupMenu();
	private Object currentContextObject = null;
	
	private LoggerFrame frame ;
	
	/** Creates new form ContextTreePanel */
	/** creates a tree displaying all the major components in a context */
	public ContextTreePanel(runtime.Context c,  LoggerFrame frame) {
		initComponents();
		this.context = c ;
		this.frame = frame ;
		ScenarioContextNode scenarioNode = new ScenarioContextNode( context,  frame) ;
		contextTree.setModel( new DefaultTreeModel( scenarioNode ));
		CustomTreeRenderer render = new CustomTreeRenderer();
		contextTree.setCellRenderer(render);
		add(contextTree ) ;
	}
	
	/** Set a descriptionPane for this panel to write information into */
	public void setDescriptionPane(JTextPane descriptionPane) {
		this.descriptionPane = descriptionPane;
	}
	
	/** get the jtree of this panel *
	 *@return JTree
	 */
	public JTree getTree() {
		return contextTree ;
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        contextTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(150, 200));
        contextTree.setDragEnabled(true);
        contextTree.setEditable(true);
        contextTree.setPreferredSize(new java.awt.Dimension(150, 200));
        contextTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contextTreeMouseClicked(evt);
            }
        });

        add(contextTree, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
	
	private void contextTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contextTreeMouseClicked
// TODO add your handling code here:
		if (MouseEvent.BUTTON3 == evt.getButton()||MouseEvent.BUTTON2 == evt.getButton()) {
			try{
				Object p = contextTree.getClosestPathForLocation(evt.getX(), evt.getY()).getLastPathComponent();
				if (p instanceof AbstractDescriptionNode){
					AbstractDescriptionNode adn = (AbstractDescriptionNode)p;
					currentContextObject = p;
					contextMenu = adn.getContextMenu();
					JMenuItem desc = new JMenuItem();
					desc.addActionListener(new java.awt.event.ActionListener() {
						public void actionPerformed(java.awt.event.ActionEvent evt) {
							DescriptionMenuClicked(evt);
						}
					});
					desc.setText("Description");
					contextMenu.add(desc);
					contextMenu.show( this, evt.getX(), evt.getY() );
				}
			} catch(Exception e){System.out.println(e);}
		} else {
			displayDescription(contextTree.getSelectionPath().getLastPathComponent());
		}
		
	}//GEN-LAST:event_contextTreeMouseClicked
	
	private void DescriptionMenuClicked(java.awt.event.ActionEvent evt) {
		displayDescription(currentContextObject);
		contextMenu.setVisible(false);
		currentContextObject=null;
	}
	
	public void displayDescription(Object p) {
		StyledDocument doc = null , dynamicDoc = null ;
		JTextPane descriptionArea = frame.getDescriptionPane() ;
		try{
			
			if (p instanceof AbstractDescriptionNode){
				AbstractDescriptionNode ADN = (AbstractDescriptionNode)p;
				doc = ADN.getStyledDocument();
				dynamicDoc = ADN.getDynamicDescription() ;
				doc.append(dynamicDoc) ;
				try {
					descriptionArea.getDocument().remove( 0 , descriptionArea.getDocument().getLength() ) ;
					for ( int i = 0 ; i < doc.getLength() ; i++ ) {
						if ( doc.getStyledElement(i).getContent().equals("\t") )
							descriptionArea.getDocument().insertString(descriptionArea.getDocument().getLength() ,"\t", doc.getStyledElement(i).getAttributeSet()) ;
						else
							descriptionArea.getDocument().insertString(descriptionArea.getDocument().getLength() ,doc.getStyledElement(i).getContent() + "\n", doc.getStyledElement(i).getAttributeSet()) ;
					}
				}
				
				catch(Exception e) {}
			}
		}
		
		catch(NullPointerException e) {
		}
		
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree contextTree;
    // End of variables declaration//GEN-END:variables
}
