/*
 * DebugControlPanel.java
 *
 * Created on September 16, 2005, 5:15 PM
 */

package verifier;

import metamodel.Scenario;
import runtime.DomainContext;

/**
 *
 * @author  u3958283
 */
public class DebugControlPanel extends javax.swing.JPanel {
	
	private DomainContext context = null;
	private Scenario scenario = null;
	private ScenarioExecutor parent;
	private Thread scenarioThread = null;

	
	
	/** Creates new form BeanForm */
	public DebugControlPanel() {
		initComponents();
	}
	
	public void init(DomainContext c, Scenario s, ScenarioExecutor se) {
		//playButton.setEnabled(false);
		pauseButton.setEnabled(false) ; 
		stopButton.setEnabled(false) ; 
		playButton.setEnabled(true);
		this.context = c;
		this.scenario = s;
		this.parent = se;

		timeSlider.initialise( context ) ; 	
	}
	
	
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        playButton = new javax.swing.JButton();
        seperator1 = new javax.swing.JSeparator();
        stopButton = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        pauseButton = new javax.swing.JButton();
        panelTimeSeparator = new javax.swing.JSeparator();
        timeSlider = new verifier.TimeSlider();

        addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                formVetoableChange(evt);
            }
        });

        playButton.setBackground(new java.awt.Color(255, 255, 255));
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verifier/play.gif")));
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        add(playButton);

        add(seperator1);

        stopButton.setBackground(new java.awt.Color(255, 255, 255));
        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verifier/stop.gif")));
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButtonMouseClicked(evt);
            }
        });

        add(stopButton);

        add(separator2);

        pauseButton.setBackground(new java.awt.Color(255, 255, 255));
        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verifier/pause.gif")));
        pauseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseButtonMouseClicked(evt);
            }
        });

        add(pauseButton);

        panelTimeSeparator.setForeground(new java.awt.Color(255, 255, 255));
        panelTimeSeparator.setPreferredSize(new java.awt.Dimension(20, 0));
        add(panelTimeSeparator);

        add(timeSlider);

    }
    // </editor-fold>//GEN-END:initComponents

	private void formVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_formVetoableChange

	}//GEN-LAST:event_formVetoableChange
			
	private void pauseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseClicked
// TODO add your handling code here:
		if (pauseButton.isEnabled()) {
			context.getDebugObject().pauseModel();
			timeSlider.refreshTime() ; 
			pauseButton.setEnabled( false ) ;
			playButton.setEnabled(true);
		}
		parent.refreshTree() ;
	}//GEN-LAST:event_pauseButtonMouseClicked
	
	private void stopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseClicked
// TODO add your handling code here:
		if (stopButton.isEnabled()) {
			context.getDebugObject().stopModel() ;
			stopButton.setEnabled( false ) ;
			pauseButton.setEnabled( false ) ;
			playButton.setEnabled( false ) ;
		}
		parent.refreshTree() ;
	}//GEN-LAST:event_stopButtonMouseClicked
	
	private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
// TODO add your handling code here:
		if( scenarioThread == null ) {
			scenarioThread = new Thread( parent );
			scenarioThread.start();
		} else {
			context.getDebugObject().runModel();
		}

		stopButton.setEnabled( true );
		pauseButton.setEnabled( true );
		playButton.setEnabled( false );
	}//GEN-LAST:event_playButtonMouseClicked
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator panelTimeSeparator;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton playButton;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator seperator1;
    private javax.swing.JButton stopButton;
    private verifier.TimeSlider timeSlider;
    // End of variables declaration//GEN-END:variables
}

