/*
 * DescriptionPanel.java
 *
 * Created on September 9, 2005, 1:12 PM
 *
 * Copyright (C) 2005 Shokouhmand Torabi
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

package verifier;

/**
 *
 * @author  Shokouhmand Torabi
 */
public class DescriptionPanel extends javax.swing.JPanel {
	
	/** Creates new form DescriptionPanel */
	public DescriptionPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        horizontalSplit = new javax.swing.JSplitPane();
        informationLabel = new javax.swing.JLabel();
        descriptionPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        horizontalSplit.setBorder(null);
        horizontalSplit.setDividerSize(0);
        horizontalSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        informationLabel.setFont(new java.awt.Font("Dialog", 1, 14));
        informationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informationLabel.setText("Componenet Information");
        horizontalSplit.setLeftComponent(informationLabel);

        descriptionPane.setEditable(false);
        descriptionPane.setMinimumSize(new java.awt.Dimension(400, 21));
        descriptionPane.setPreferredSize(new java.awt.Dimension(400, 21));
        horizontalSplit.setRightComponent(descriptionPane);

        add(horizontalSplit, java.awt.BorderLayout.NORTH);

    }
    // </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane descriptionPane;
    private javax.swing.JSplitPane horizontalSplit;
    private javax.swing.JLabel informationLabel;
    // End of variables declaration//GEN-END:variables
	
}
