/*
 * LoggerFrame.java
 *
 * Created on September 6, 2005, 3:52 PM
 */

package verifier;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author  David Gavin
 */
public class LoggerFrame extends javax.swing.JFrame {
	private ScenarioExecuter scenarioExec;
        private ModelTreePanel mtp;
	/** Creates new form LoggerFrame */
	public LoggerFrame() {
		initComponents();
                URL imageURL = getClass().getClassLoader().getResource("verifier/lem.jpg");
		Image lem = Toolkit.getDefaultToolkit().getImage(imageURL);
		setIconImage(lem);
	}
	public void setScenarioExecutor(ScenarioExecuter inScenarioExec){
            scenarioExec = inScenarioExec;
		this.add(scenarioExec);
		this.setTitle(scenarioExec.getScenarioName()+" Scenario");
        }
        
        public void setParent(ModelTreePanel inMTP)
        {
            mtp=inMTP;
        }
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
	 scenarioExec.killScenario();
         mtp.killLogger(this);
	}//GEN-LAST:event_formWindowClosing
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	
}
