/*
 * GenerateStatechartDialog.java
 *
 * Created on 8 July 2005, 21:38
 */

package verifier;

/**
 *
 * @author  gen
 */
public class GenerateStatechartDialog extends javax.swing.JDialog {
	
	/**
	 * Creates new form GenerateStatechartDialog 
	 */
	public GenerateStatechartDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    gridLayout1 = new java.awt.GridLayout();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setName("Generate Statechart");
    jLabel1.setText("Test label:");
    getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

    jTextField1.setText("jTextField1");
    getContentPane().add(jTextField1, java.awt.BorderLayout.EAST);

    pack();
  }
  // </editor-fold>//GEN-END:initComponents
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.GridLayout gridLayout1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
	
}
